import { jsPDF } from "jspdf"

export function generatePDF(letterContent: string, title: string): Buffer {
  const doc = new jsPDF()

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const marginLeft = 20
  const marginRight = 20
  const contentWidth = pageWidth - marginLeft - marginRight
  const headerHeight = 25
  const footerY = pageHeight - 15
  const maxContentY = footerY - 10

  function addHeaderAndFooter() {
    // Header branding
    doc.setFontSize(10)
    doc.setTextColor(13, 148, 136) // teal
    doc.text("Generated by BillFight.co", marginLeft, 15)
    doc.setDrawColor(13, 148, 136)
    doc.line(marginLeft, 18, pageWidth - marginRight, 18)

    // Footer disclaimer
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text(
      "This document was generated by BillFight.co and does not constitute legal advice.",
      marginLeft,
      footerY
    )
  }

  // Add title
  addHeaderAndFooter()
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text(title, marginLeft, headerHeight + 10)

  // Add letter content with word wrapping and multi-page support
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  const lines = doc.splitTextToSize(letterContent, contentWidth)
  const lineHeight = 6
  let cursorY = headerHeight + 22

  for (let i = 0; i < lines.length; i++) {
    if (cursorY + lineHeight > maxContentY) {
      doc.addPage()
      addHeaderAndFooter()
      cursorY = headerHeight + 5
    }
    doc.text(lines[i], marginLeft, cursorY)
    cursorY += lineHeight
  }

  return Buffer.from(doc.output("arraybuffer"))
}
